import Link from "next/link";
import { studentLearning } from "@/lib/lms/student-data";
import { completedGames, learningState, learningDate } from "@/lib/lms/student-portal";
import { Workspace, Card, Empty } from "@/components/LmsUi";
export default async function ProgressPage() {
  const { learning } = await studentLearning(), done = learning.reduce((n,l) => n+completedGames(l),0), total = learning.reduce((n,l) => n+l.games.length,0);
  const recent = learning.flatMap(l => l.attempts.map(a => ({a,l}))).sort((x,y) => Date.parse(y.a.started_at)-Date.parse(x.a.started_at)).slice(0,10);
  return <Workspace title="My Progress" description="See how far you have come.">{learning.length ? <div className="stack-layout"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[["Learning Paths completed",learning.filter(l => l.boardId && learningState(l)==="Completed").length],["Games completed",done],["Learning Paths in progress",learning.filter(l => l.boardId && learningState(l)==="Current" && l.attempts.length).length],["Overall completion",`${total ? Math.round(done/total*100) : 0}%`]].map(([label,value]) => <Card key={label}><p className="text-sm text-[#667085]">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></Card>)}</div><Card><h2 className="mb-4 text-lg font-bold">Recent learning</h2>{recent.length ? <ul className="divide-y divide-[#E3E8F2]">{recent.map(({a,l}) => <li key={a.id} className="flex flex-wrap justify-between gap-2 py-3"><div><Link className="font-semibold text-[#4F46E5]" href={`/student/learning/${encodeURIComponent(l.key)}`}>{l.title}</Link><p className="text-sm text-[#667085]">{(l.games.find(g=>g.id===a.game_id) || l.historicalGames?.find(g=>g.id===a.game_id))?.name} · {a.completion_status === "completed" ? "Completed" : a.has_started ? "In progress" : "Not started"}</p></div><time className="text-sm text-[#667085]">{learningDate(a.completed_at || a.started_at)}</time></li>)}</ul> : <p className="text-sm text-[#667085]">Start a game to see your progress here.</p>}</Card></div> : <Empty title="Your progress starts here">Your learning progress will appear when your teacher assigns learning.</Empty>}</Workspace>;
}
