const test=require('node:test'),assert=require('node:assert/strict'),mock=require('./mock-module.cjs'),load=require('./load-typescript.cjs');
const {signPreview,verifyPreview}=load('lib/scorm/preview-token.ts');
const id='00000000-0000-0000-0000-000000000001',claim={user:id,game:id,package:id,expires:2000};
test('preview tokens reject tampering, expiration, and wrong signing keys',()=>{const t=signPreview(claim,'secret');assert.deepEqual(verifyPreview(t,'secret',1000),claim);assert.throws(()=>verifyPreview(t,'other',1000));assert.throws(()=>verifyPreview(t+'x','secret',1000));assert.throws(()=>verifyPreview(t,'secret',2000))});
class LmsError extends Error{constructor(m,status=400){super(m);this.status=status;}}
const auth={checkDb:e=>{if(e)throw e},LmsError};
const {retentionReason}=mock('lib/scorm/cleanup-plan.ts',{'@/lib/lms/auth':auth});
const pkg={id:'old',game_id:'game',storage_path:'game/source/old.zip',extraction_path:'game/packages/old/extracted'};
test('cleanup protects active packages, all historical attempts, legacy attempts, and shared files',()=>{assert.equal(retentionReason(pkg,[pkg],[{id:'game',package_path:pkg.extraction_path}],[]),'Active game package');assert.match(retentionReason(pkg,[pkg],[],[{game_id:'game',package_id:'old'}]),/historical/);assert.match(retentionReason(pkg,[pkg],[],[{game_id:'game',package_id:null}]),/historical/);assert.match(retentionReason(pkg,[pkg,{...pkg,id:'another'}],[],[]),/Shared/);assert.equal(retentionReason(pkg,[pkg],[],[]),null)});
test('cleanup refuses traversal and unexpected directory ownership',()=>{assert.match(retentionReason({...pkg,storage_path:'game/source/../other.zip'},[pkg],[],[]),/ownership/);assert.match(retentionReason({...pkg,extraction_path:'other/extracted'},[pkg],[],[]),/ownership/)});
const preview=mock('lib/scorm/admin-preview.ts',{'@/lib/lms/auth':auth,'@/lib/supabase/admin':{},'./preview-token':{signPreview,verifyPreview}});
function schoolFixture(available){const calls=[];const db={from(table){calls.push(table);const q={select(){return q},eq(){return q},maybeSingle(){return q},then(resolve){return Promise.resolve({error:null,data:available?{id:'published-game'}:null}).then(resolve)}};return q}};return {db,calls}}
test('school preview follows shared published library access without requiring assignments',async()=>{const denied=schoolFixture(false);await assert.rejects(preview.schoolPreviewAccess(denied.db,'game','school'),e=>e.status===403);const allowed=schoolFixture(true);await preview.schoolPreviewAccess(allowed.db,'game','school');assert.deepEqual(allowed.calls,['games']);await assert.rejects(preview.schoolPreviewAccess(allowed.db,'game',null),e=>e.status===403)});
test('preview asset route serves sandboxed SCORM with browse/no-credit and no persistence endpoint',async()=>{const content=mock('app/api/admin/preview/[token]/[...path]/route.ts',{'@/lib/lms/auth':{...auth,apiError:e=>({status:e.status})},'@/lib/scorm/admin-preview':{previewContent:async()=>({admin:{storage:{from:()=>({download:async()=>({data:new Blob(['<html><head></head><body>Game</body></html>']),error:null})})}},package:{scorm_version:'1.2',extraction_path:'private',launch_file:'index.html'}})},'@/lib/scorm/bridge':load('lib/scorm/bridge.ts')});const r=await content.GET(new Request('https://example.test/api/admin/preview/token/index.html'),{params:Promise.resolve({token:'token',path:['index.html']})});assert.equal(r.status,200);const html=await r.text();assert.ok(html.includes('no-credit'));assert.ok(html.includes('browse'));assert.ok(html.includes('function tell(finish){error="0";}'));assert.equal(r.headers.get('cache-control'),'private, no-store');assert.ok(!r.headers.get('content-security-policy').includes('allow-same-origin'));assert.ok(!html.includes('/api/student/runtime'))});
