const test=require('node:test'),assert=require('node:assert/strict'),mock=require('./mock-module.cjs');
class LmsError extends Error {constructor(message,status=400){super(message);this.status=status;}}
const next={'next/server':{NextResponse:{json:(body,options={})=>({body,status:options.status||200})}}};
function publishing(skillId,skill={subject_id:'subject',is_active:true}) {
 const writes=[];const admin={from(table){let updating=false;const q={select(){return q},eq(){return q},in(){return q},limit(){return q},update(v){updating=true;writes.push(v);return q},maybeSingle(){return q},then(resolve){return Promise.resolve({error:null,data:updating?{id:'game',status:'published'}:table==='games'?{skill_id:skillId,package_path:'package',launch_file:'index.html'}:table==='skills'?skill:table==='subjects'?{id:'subject',is_active:true}:[{id:'package'}]}).then(resolve)}};return q}};
 const api=mock('app/api/admin/games/[id]/status/route.ts',{...next,'@/lib/lms/auth':{authorize:async()=>({admin}),jsonBody:async()=>({status:'published'}),uuid:v=>v,checkDb:e=>{if(e)throw e},LmsError,apiError:e=>({status:e.status,body:{error:e.message}})}});return {api,writes};
}
test('publishing rejects games without a skill or with an inactive skill before writing',async()=>{for(const f of [publishing(null),publishing('skill',{subject_id:'subject',is_active:false})]){assert.equal((await f.api.PATCH({}, {params:Promise.resolve({id:'game'})})).status,409);assert.equal(f.writes.length,0)}});
test('publishing accepts a ready game belonging to an active skill and subject',async()=>{const f=publishing('skill');assert.equal((await f.api.PATCH({}, {params:Promise.resolve({id:'game'})})).status,200);assert.equal(f.writes.length,1)});
test('path sequence sends ordered references across subjects to the existing ownership-protected RPC',async()=>{const calls=[];const api=mock('app/api/admin/paths/[id]/games/route.ts',{...next,'@/lib/lms/auth':{ownedPath:async()=>({supabase:{rpc:async(name,args)=>{calls.push({name,args});return {error:null}}}}),jsonBody:async()=>({game_ids:['addition-a','subtraction-c','multiplication-d','addition-b'],expected_updated_at:'version'}),uuid:v=>v,checkDb:e=>{if(e)throw e},LmsError,apiError:e=>({status:e.status})}});assert.equal((await api.PUT({}, {params:Promise.resolve({id:'path'})})).status,200);assert.deepEqual(calls[0].args.p_games,['addition-a','subtraction-c','multiplication-d','addition-b']);assert.equal(calls[0].name,'learnboard_save_path_games')});
