"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Card, Field, inputClass, buttonClass } from "./LmsUi";
import { submitJson, useToast } from "./LmsToast";
export default function AccountSettings({ name, email, role }: { name: string; email: string; role: string }) {
  const [fullName, setFullName] = useState(name), [current, setCurrent] = useState(""), [password, setPassword] = useState(""), [confirm, setConfirm] = useState(""), [busy, setBusy] = useState(false);
  const router = useRouter(); const { notification, setToast } = useToast();
  async function save(e: FormEvent, action: string) { e.preventDefault(); if (action === "password" && password !== confirm) { setToast({ type: "error", message: "The new passwords do not match." }); return; } setBusy(true); try { await submitJson("/api/account/settings", "PATCH", action === "profile" ? { action, full_name: fullName } : { action, current_password: current, new_password: password }); if (action === "password") { setCurrent(""); setPassword(""); setConfirm(""); } setToast({ type: "success", message: action === "profile" ? "Profile updated." : "Password updated." }); router.refresh(); } catch(e) { setToast({ type: "error", message: (e as Error).message }); } finally { setBusy(false); } }
  return <>{notification}<div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="mb-5 text-lg font-bold text-[#172033]">Account</h2><form className="space-y-5" onSubmit={e => save(e,"profile")}><Field label="Full name"><input required maxLength={150} className={inputClass} value={fullName} disabled={busy} onChange={e => setFullName(e.target.value)} /></Field><Field label="Email"><input readOnly className={inputClass} value={email} /></Field><p className="text-sm text-[#667085]">Role: {role === "super_admin" ? "Super Admin" : role === "admin" ? "School Admin / Teacher" : "Student"}</p><button disabled={busy} className={buttonClass}>Save Profile</button></form></Card><Card><h2 className="mb-5 text-lg font-bold text-[#172033]">Change Password</h2><form className="space-y-5" onSubmit={e => save(e,"password")}><Field label="Current password"><input required autoComplete="current-password" type="password" className={inputClass} disabled={busy} value={current} onChange={e => setCurrent(e.target.value)} /></Field><Field label="New password"><input required autoComplete="new-password" type="password" minLength={8} maxLength={128} className={inputClass} disabled={busy} value={password} onChange={e => setPassword(e.target.value)} /></Field><Field label="Confirm new password"><input required autoComplete="new-password" type="password" minLength={8} maxLength={128} className={inputClass} disabled={busy} value={confirm} onChange={e => setConfirm(e.target.value)} /></Field><button disabled={busy} className={buttonClass}>Update Password</button></form></Card></div></>;
}
