"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import ActionIcon from "./ActionIcon";
import { buttonClass, secondaryClass, inputClass } from "./LmsUi";
import { submitJson, useToast } from "./LmsToast";
import ScheduleDateTime from "./ScheduleDateTime";
import type { Assignment } from "@/lib/lms/types";
type Student = { id: string; full_name: string | null; email: string; is_active: boolean };
const defaults={available_from:"",available_until:"",allow_resume:true};
function localDate(value:string|null){if(!value)return "";const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export default function PathStudents({pathId,active}:{pathId:string;active:boolean}) {
 const router=useRouter(),{setToast}=useToast();
 const [students,setStudents]=useState<Student[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[search,setSearch]=useState(""),[selected,setSelected]=useState<string[]>([]);
 const [editing,setEditing]=useState<Assignment|null>(null),[adding,setAdding]=useState(false),[removing,setRemoving]=useState<Assignment|null>(null),[schedule,setSchedule]=useState(defaults);
 const dialog=useRef<HTMLDialogElement>(null);
 const load=useCallback(async()=>{try{const response=await fetch(`/api/admin/paths/${pathId}/students`,{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to load students.");setStudents(data.students);setAssignments(data.assignments);setLoaded(true);}catch(e){setToast({type:"error",message:(e as Error).message});}},[pathId,setToast]);
 useEffect(()=>{void Promise.resolve().then(()=>load());},[load]);
 useEffect(()=>{if(adding||editing||removing)dialog.current?.showModal();else dialog.current?.close();},[adding,editing,removing]);
 function close(){if(busy)return;setAdding(false);setEditing(null);setRemoving(null);}
 const direct=assignments.filter(a=>!a.group_assignment_id),current=direct.filter(a=>a.status!=="cancelled"),assigned=new Set(assignments.filter(a=>a.status!=="cancelled").map(a=>a.student_id));
 const eligible=students.filter(s=>s.is_active&&!assigned.has(s.id));
 function edit(item:Assignment){setEditing(item);setSchedule({available_from:localDate(item.available_from),available_until:localDate(item.available_until),allow_resume:item.allow_resume});}
 async function save(){if(busy)return;setBusy(true);let saved=0;try{
  const targets=editing?[editing.student_id]:selected;
  for(const target of targets){const prior=editing||direct.find(a=>a.student_id===target&&a.status==="cancelled");await submitJson("/api/admin/assignments",prior?"PATCH":"POST",{kind:"student",id:prior?.id,board_id:pathId,target_id:target,...schedule,available_from:schedule.available_from?new Date(schedule.available_from).toISOString():null,available_until:schedule.available_until?new Date(schedule.available_until).toISOString():null,max_attempts:1,time_limit_minutes:null,passing_score:prior?.passing_score??70,status:"active"});saved++;}
  setToast({type:"success",message:editing?"Student schedule saved.":`${saved} ${saved===1?"student added":"students added"}.`});setAdding(false);setEditing(null);setSelected([]);
 }catch(e){setToast({type:"error",message:`${saved?`${saved} students were saved. `:""}${(e as Error).message}`});if(!editing)setSelected(targetsAfterSaved(selected,saved));}finally{await load();setBusy(false);router.refresh();}}
 async function remove(){if(!removing||busy)return;setBusy(true);try{await submitJson(`/api/admin/paths/${pathId}/students`,"DELETE",{assignment_id:removing.id});setToast({type:"success",message:"Student removed from this path. Progress remains saved."});setRemoving(null);}catch(e){setToast({type:"error",message:(e as Error).message});}finally{await load();setBusy(false);router.refresh();}}
 const name=(id:string)=>{const student=students.find(s=>s.id===id);return student?.full_name||student?.email||"Student";};
 return <section className="rounded-2xl border border-[#E3E8F2] bg-white p-5 text-[#172033] shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">Students ({assigned.size})</h2><button type="button" className={secondaryClass} disabled={!active||busy} onClick={()=>{setSelected([]);setSearch("");setSchedule(defaults);setAdding(true);}}><ActionIcon name="add"/>Add</button></div><p className="mt-2 text-xs leading-5 text-[#667085]">Manage access and schedules. Saved progress stays with each student.</p>
 {!loaded?<button type="button" className={`${secondaryClass} mt-3`} onClick={()=>void load()}>Load students</button>:<><ul className="mt-4 max-h-80 space-y-3 overflow-y-auto">{current.map(a=><li key={a.id} className="rounded-xl border border-[#E3E8F2] p-3"><p className="break-words text-sm font-semibold">{name(a.student_id)}</p><p className="mt-1 text-xs text-[#667085]">{a.available_from?new Date(a.available_from).toLocaleString():"Available immediately"}{a.available_until?` · Until ${new Date(a.available_until).toLocaleString()}`:" · No closing date"}</p><div className="mt-2 flex gap-2"><button type="button" disabled={busy} className={`${secondaryClass} min-h-8 text-xs`} onClick={()=>edit(a)}>Schedule</button><button type="button" disabled={busy} className="rounded-lg px-2 text-xs font-semibold text-red-700 hover:bg-red-50" onClick={()=>setRemoving(a)}>Remove</button></div></li>)}</ul>{!current.length&&<p className="mt-4 text-sm text-[#667085]">No individually assigned students.</p>}{assignments.some(a=>a.group_assignment_id&&a.status!=="cancelled")&&<p className="mt-3 text-xs text-[#667085]">Students assigned through a class are managed through that class assignment.</p>}</>}
 <dialog ref={dialog} onCancel={e=>{e.preventDefault();close();}} onClose={()=>{if(!busy){setAdding(false);setEditing(null);setRemoving(null);}}} className="m-auto w-[min(640px,calc(100%_-_32px))] max-h-[90dvh] overflow-y-auto rounded-2xl border border-[#E3E8F2] p-0 shadow-xl backdrop:bg-slate-900/40"><div className="flex items-start justify-between border-b border-[#E3E8F2] p-6"><div><h2 className="text-xl font-bold text-[#172033]">{removing?"Remove Student":editing?"Student Schedule":"Add Students"}</h2><p className="mt-1 text-sm text-[#667085]">{removing?name(removing.student_id):editing?name(editing.student_id):"Choose students and when they can access this path."}</p></div><button type="button" aria-label="Close" disabled={busy} onClick={close} className="rounded-lg p-2 text-slate-500 hover:bg-slate-50"><ActionIcon name="close"/></button></div>
 {removing?<div className="p-6"><p className="text-sm leading-6 text-[#344054]">Remove this student from this learning path? Their scores and history stay saved. An already-open game can finish; further launches are blocked.</p><div className="mt-6 flex justify-end gap-3"><button type="button" disabled={busy} className="rounded-xl border border-[#D8DEEA] px-4 py-2 text-sm font-semibold text-[#344054]" onClick={close}>Cancel</button><button type="button" disabled={busy} className={`${buttonClass} !bg-red-600 hover:!bg-red-700`} onClick={remove}>{busy?"Removing...":"Remove Student"}</button></div></div>:<form onSubmit={e=>{e.preventDefault();void save();}} className="p-6"><fieldset disabled={busy} className="space-y-5">{adding&&<div><input aria-label="Search students" className={inputClass} placeholder="Search students..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="mt-3 max-h-44 space-y-2 overflow-y-auto">{eligible.filter(s=>`${s.full_name||""} ${s.email}`.toLowerCase().includes(search.toLowerCase())).map(s=><label key={s.id} className="flex items-center gap-3 rounded-xl border border-[#E3E8F2] p-3 text-sm"><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/>{s.full_name||s.email}</label>)}</div>{!eligible.length&&<p className="mt-3 text-sm text-[#667085]">All active students are already assigned.</p>}</div>}
 <div className="rounded-xl border border-[#E3E8F2] bg-white"><div className="grid gap-5 sm:grid-cols-2 p-4"><ScheduleDateTime label="Available from" value={schedule.available_from} onChange={value=>setSchedule({...schedule,available_from:value})} help="Leave blank to open immediately."/><ScheduleDateTime label="Expires on" required value={schedule.available_until} min={schedule.available_from} onChange={value=>setSchedule({...schedule,available_until:value})} help="Games close at this date and time."/></div></div><div className="flex items-center justify-between gap-4 rounded-xl border border-[#E3E8F2] px-4 py-3"><div><h3 className="text-sm font-semibold text-[#344054]">Allow resume</h3><p id="resume-description" className="mt-1 text-xs text-[#667085]">{schedule.allow_resume?"Students can continue before expiration.":"Leaving the game ends their chance."}</p></div><button type="button" role="switch" aria-label="Allow resume" aria-describedby="resume-description" aria-checked={schedule.allow_resume} onClick={()=>setSchedule({...schedule,allow_resume:!schedule.allow_resume})} className={"relative h-6 w-11 shrink-0 rounded-full transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#6366F1] "+(schedule.allow_resume?"bg-[#6366F1]":"bg-[#CBD5E1]")}><span className={"absolute top-0.5 h-5 w-5 rounded-full bg-white shadow-sm transition-all "+(schedule.allow_resume?"left-[22px]":"left-0.5")}/></button></div><p className="text-xs leading-5 text-[#667085]">Each student gets one chance per game. The expiration applies to every game in this path, including resumed games.</p></fieldset><div className="mt-6 flex justify-end gap-3 border-t border-[#E3E8F2] pt-5"><button type="button" disabled={busy} className="rounded-xl border border-[#D8DEEA] px-4 py-2 text-sm font-semibold text-[#344054]" onClick={close}>Cancel</button><button disabled={busy||(!editing&&!selected.length)} className={buttonClass}><ActionIcon name="save"/>{busy?"Saving...":editing?"Save Schedule":"Add Students"}</button></div></form>}
 </dialog></section>;
}
function targetsAfterSaved(selected:string[],saved:number){return selected.slice(saved);}
