"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { Game } from "@/lib/lms/types";
import { Card, Empty, buttonClass, secondaryClass, inputClass } from "./LmsUi";
import { useToast, submitJson } from "./LmsToast";
export default function PathGamesEditor({ pathId, updatedAt, games, selected, subjects }: { pathId: string; updatedAt: string; games: Game[]; selected: string[]; subjects: { id: string; name: string }[] }) {
  const router = useRouter();
  const [ids, setIds] = useState(selected), [search, setSearch] = useState(""), [subject, setSubject] = useState("all"), [busy, setBusy] = useState(false);
  const { notification, setToast } = useToast();
  const move = (index: number, delta: number) => setIds(current => { const next = [...current]; [next[index], next[index + delta]] = [next[index + delta], next[index]]; return next; });
  async function save() { setBusy(true); try { await submitJson(`/api/admin/paths/${pathId}/games`, "PUT", { game_ids: ids, expected_updated_at: updatedAt }); setToast({ type: "success", message: "Game sequence saved." }); router.refresh(); } catch (e) { setToast({ type: "error", message: (e as Error).message }); } finally { setBusy(false); } }
  return <>{notification}<div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="mb-4 text-lg font-bold text-[#172033]">Games in this Path ({ids.length})</h2>{ids.length ? <ol className="space-y-3">{ids.map((id, i) => <li key={id} className="flex flex-wrap items-center gap-2 rounded-xl border border-[#E3E8F2] p-3"><span className="flex-1 text-sm font-semibold text-[#344054]">{i + 1}. {games.find(g => g.id === id)?.name || "Unavailable game"}</span><button className={secondaryClass} aria-label="Move up" disabled={busy || i === 0} onClick={() => move(i, -1)}>↑</button><button className={secondaryClass} aria-label="Move down" disabled={busy || i === ids.length - 1} onClick={() => move(i, 1)}>↓</button><button className={secondaryClass} disabled={busy} onClick={() => setIds(ids.filter(v => v !== id))}>Remove</button></li>)}</ol> : <Empty title="No games selected" />}<button className={`${buttonClass} mt-5`} disabled={busy} onClick={save}>{busy ? "Saving..." : "Save Sequence"}</button></Card><Card><h2 className="mb-4 text-lg font-bold text-[#172033]">Global Games Library</h2><div className="mb-4 space-y-3"><input className={inputClass} aria-label="Search games" placeholder="Search games..." value={search} onChange={e => setSearch(e.target.value)} /><select className={inputClass} aria-label="Subject" value={subject} onChange={e => setSubject(e.target.value)}><option value="all">All Subjects</option>{subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="max-h-[600px] space-y-3 overflow-y-auto">{games.filter(g => g.name.toLowerCase().includes(search.toLowerCase()) && (subject === "all" || g.subject_id === subject)).map(g => <div key={g.id} className="flex items-center gap-3 rounded-xl border border-[#E3E8F2] p-3"><div className="flex-1"><p className="text-sm font-semibold text-[#344054]">{g.name}</p><p className="text-xs text-[#667085]">{g.status === "published" ? "Published" : "Draft"}</p></div><button className={secondaryClass} disabled={busy || ids.includes(g.id) || ids.length >= 200} onClick={() => setIds([...ids, g.id])}>{ids.includes(g.id) ? "Added" : "Add"}</button></div>)}</div></Card></div></>;
}
