"use client";
import { type PlayRestrictions } from "./StudentPlayNotice";
import LaunchLearningButton from "./LaunchLearningButton";
﻿
import { useRef, useState } from "react";
import ActionIcon from "./ActionIcon";
import { buttonClass, secondaryClass } from "./LmsUi";
export type ScoreHistory = { id:string; date:string; score:string; progress:string; accuracy:string; result:string; correct:number|null; incorrect:number|null; elapsed:string; questions:{question:string; attempt:number; result:string; speed:string}[] };
export type ScoreRow = { id:string; title:string; image:string|null; learningPath:string; resume:{restrictions:PlayRestrictions; assignmentId:string|null; classAssignmentId:string|null; gameId:string}|null; history:ScoreHistory[] };
export default function StudentScoresTable({rows}:{rows:ScoreRow[]}) {
 const dialog=useRef<HTMLDialogElement>(null),[selectedId,setSelectedId]=useState<string|null>(null);
 const selected=rows.find(row=>row.id===selectedId);
 function open(row:ScoreRow){setSelectedId(row.id);dialog.current?.showModal();}
 return <><div className="space-y-2 text-sm"><div className="hidden grid-cols-[6rem_1fr_1.4fr_1fr_1fr_auto] gap-4 px-3 py-3 font-semibold text-[#667085] md:grid">{["Image","Game","Learning Path","Score","Progress",""].map(label=><span key={label}>{label}</span>)}</div>{rows.map(row=><article key={row.id} className="grid grid-cols-2 items-center gap-4 rounded-xl px-3 py-4 md:grid-cols-[6rem_1fr_1.4fr_1fr_1fr_auto]">{row.image ? <img src={row.image} alt="" className="aspect-[4/3] w-20 rounded-lg object-cover"/> : <span>No image</span>}<h3 className="font-semibold">{row.title}</h3><div><span className="block text-xs text-[#667085] md:hidden">Learning Path</span>{row.learningPath}</div><div><span className="block text-xs text-[#667085] md:hidden">Score</span>{row.history[0].score}</div><div><span className="block text-xs text-[#667085] md:hidden">Progress</span>{row.history[0].progress}</div><button className={buttonClass} onClick={()=>open(row)} aria-label={"View results for "+row.title}><ActionIcon name="view" />View</button></article>)}</div>
 <dialog ref={dialog} aria-labelledby="result-title" className="m-auto max-h-[90dvh] w-[min(72rem,calc(100vw-2rem))] overflow-y-auto rounded-2xl bg-white p-6 text-[#172033] shadow-xl backdrop:bg-black/50" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}}>
 {selected && <><div className="flex items-start justify-between gap-4"><h2 id="result-title" className="text-2xl font-bold">{selected.title}</h2><button className={(secondaryClass + " !border-[#DDD6FE] !bg-[#EDE9FE] !text-[#6D28D9] hover:!bg-[#DDD6FE]") + " !border-red-200 !bg-red-50 !text-red-700 hover:!bg-red-100 focus-visible:!outline-red-500 focus:!ring-red-200"} onClick={()=>dialog.current?.close()}><ActionIcon name="close" />Close</button></div><div className="my-5 grid items-stretch gap-8 sm:grid-cols-[10rem_minmax(0,1fr)]">{selected.image && <img src={selected.image} alt="" className="aspect-[4/3] w-40 max-w-full rounded-xl object-cover"/>}<div className="flex flex-col justify-center gap-3 sm:min-h-[7.5rem]"><dl className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Learning Path",selected.learningPath],["Score",selected.history[0].score],["Progress",selected.history[0].progress],["Accuracy",selected.history[0].accuracy],["Time played",selected.history[0].elapsed]].map(([label,value])=><div key={label}><dt className="text-sm text-[#667085]">{label}</dt><dd className="mt-1 text-lg font-semibold">{value}</dd></div>)}</dl>{selected.resume && <div><LaunchLearningButton {...selected.resume} disabled={false} label="Continue game" /></div>}</div></div><h3 className="mb-3 text-xl font-bold">Detailed history</h3><div className="space-y-4">{selected.history.map(h=><section key={h.id} className="rounded-xl border border-[#E3E8F2] p-4"><p className="font-semibold">{h.date}</p>{h.questions.length ? <table className="mt-4 w-full border-collapse border border-[#D0D5DD] text-left text-sm"><thead><tr><th scope="col" className="border border-[#D0D5DD] bg-[#EAECF0] px-3 py-3">Question</th><th className="px-3 py-2">Attempt</th><th className="px-3 py-2">Result</th><th className="px-3 py-2">Speed</th></tr></thead><tbody>{h.questions.map((q,i)=><tr key={i} className={"border-t border-[#E3E8F2] " + ([...new Set(h.questions.map(item=>item.question))].indexOf(q.question)%2===0 ? "bg-[#F3F4F6]" : "bg-[#F9FAFB]")}><td className="px-3 py-3">{q.question}</td><td className="px-3 py-3">{q.attempt}</td><td className="px-3 py-3"><span className={"inline-flex rounded-full px-2.5 py-1 text-xs font-semibold " + (q.result==="Correct" ? "bg-[#DCFCE7] text-[#166534]" : q.result==="Incorrect" ? "bg-[#FEE2E2] text-[#991B1B]" : "bg-[#E5E7EB] text-[#374151]")}>{q.result}</span></td><td className="px-3 py-3">{q.speed}</td></tr>)}</tbody></table> : <p className="mt-4 text-sm text-[#667085]">No question details available.</p>}</section>)}</div></>}
 </dialog></>;
}
