import { studentLearning } from "@/lib/lms/student-data";
import { learningDate, gameImage } from "@/lib/lms/student-portal";
import { Workspace, Card, Empty, inputClass, secondaryClass } from "@/components/LmsUi";
export default async function ScoresPage({searchParams}:{searchParams:Promise<{learning?:string}>}) {
  const { learning } = await studentLearning(), filter = (await searchParams).learning;
  const rows = learning.filter(l => !filter || l.key === filter).flatMap(l=>l.attempts.map(a=>({a,l}))).sort((x,y)=>Date.parse(y.a.started_at)-Date.parse(x.a.started_at));
  const grades = rows.map(r=>r.a.score).filter((s):s is number=>s!==null), completed = new Set(rows.filter(r=>r.a.completion_status==="completed").map(r=>r.a.game_id)).size;
  return <Workspace title="My Scores" description="Your results and complete attempt history."><div className="stack-layout"><div className="grid gap-5 sm:grid-cols-2">{[["Average Score",grades.length ? `${Math.round(grades.reduce((n,s)=>n+s,0)/grades.length)}%` : "—"],["Games Completed",completed],["Best Score",grades.length ? `${Math.round(Math.max(...grades))}%` : "—"]].map(([label,value])=><Card key={label}><p className="text-sm text-[#667085]">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></Card>)}</div><form className="flex flex-wrap gap-3"><label className="min-w-0 flex-1"><span className="sr-only">Filter by learning</span><select name="learning" defaultValue={filter || ""} className={inputClass}><option value="">All learning</option>{learning.map(l=><option key={l.key} value={l.key}>{l.title}</option>)}</select></label><button className={secondaryClass}>Filter</button></form>{rows.length ? <Card><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-[#667085]"><tr>{["Image","Game","Learning Path","Attempt","Score","Completion","Result","Date"].map(h=><th key={h} className="whitespace-nowrap px-3 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#E3E8F2]">{rows.map(({a,l})=><tr key={a.id}><td className="px-3 py-4"><div className="aspect-[4/3] w-20 overflow-hidden rounded-lg bg-[#EEF0FF]">{gameImage(l.games.find(g=>g.id===a.game_id)?.image_path || null) ? <img src={gameImage(l.games.find(g=>g.id===a.game_id)?.image_path || null)!} alt="" className="h-full w-full object-cover" /> : <span className="flex h-full items-center justify-center text-xs text-[#667085]">No image</span>}</div></td><td className="px-3 py-4 font-semibold">{l.games.find(g=>g.id===a.game_id)?.name || "Game"}</td><td className="px-3 py-4">{l.title}</td><td className="px-3 py-4">{a.attempt_number}</td><td className="px-3 py-4">{l.score_visible===false ? "Hidden by your teacher" : a.score===null ? "Not scored" : `${Math.round(a.score)}%`}</td><td className="px-3 py-4">{a.completion_status==="completed" ? "Completed" : "In progress"}</td><td className="px-3 py-4">{a.success_status==="passed" ? "Passed" : a.success_status==="failed" ? "Not passed" : "—"}</td><td className="whitespace-nowrap px-3 py-4">{learningDate(a.completed_at || a.started_at)}</td></tr>)}</tbody></table></div></Card> : <Empty title="No results yet">Your attempt history will appear here after you start learning.</Empty>}</div></Workspace>;
}
